version: '3.3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - ./.env
  # server:
  #   container_name: rust-server
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file: .env
  #   depends_on:
  #     - database
  #   networks:
  #     - default
  #   ports:
  #     - "8080:8080"
volumes:
  data:
